package hello.dao;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import hello.model.Elevator;

@Repository
public interface FloorRepository extends JpaRepository<Elevator, Integer> {

	/**
	 * By implementing JpaRepository, all of the following methods are auto generated by spring
	 * to access the underline table with CRUD function
	 */
	//findAll()
	//findAll(Sort)
	//findAll(Iterable<ID>)
	//save(Iterable<S>)
	//flush()
	//saveAndFlush(S)
	//deleteInBatch(Iterable<T>)
	//deleteAllInBatch()
	//getOne(ID)
	//findAll(Example<S>)
	//findAll(Example<S>, Sort)
}
